Repository hanium-where2go/where2go-backend, pull requests merged in 2023-08, with the labels that each got.

#50 [Feat] #49 레스토랑 대표 리뷰 3개 조회기능 추가
  src/main/java/hanium/where2go/domain/reservation/controller/ReservationController.java
  src/main/java/hanium/where2go/domain/reservation/dto/HashtagResponseDto.java
  src/main/java/hanium/where2go/domain/restaurant/repository/ReviewRepository.java
  src/main/java/hanium/where2go/domain/restaurant/service/ReviewService.java
Labels: enhancement

#59 [Feat] #42 map api 구현
  build.gradle
  src/main/java/hanium/where2go/domain/restaurant/controller/MapController.java
  src/main/java/hanium/where2go/domain/restaurant/dto/MapDto.java
  src/main/java/hanium/where2go/domain/restaurant/service/MapService.java
  src/main/java/hanium/where2go/domain/restaurant/service/MapServiceImpl.java
  src/main/java/hanium/where2go/global/config/SecurityConfig.java
  src/main/java/hanium/where2go/global/utils/MapResponseMapper.java
  src/main/java/hanium/where2go/global/utils/MapUtils.java
Labels: enhancement, fix

#66 [Feat] #65 RestaurantDto seperation
  src/main/java/hanium/where2go/domain/restaurant/controller/RestaurantController.java
  src/main/java/hanium/where2go/domain/restaurant/dto/CommonInformationResponseDto.java
  src/main/java/hanium/where2go/domain/restaurant/dto/InformationResponseDto.java
  src/main/java/hanium/where2go/domain/restaurant/dto/MapDto.java
  src/main/java/hanium/where2go/domain/restaurant/dto/MenuDetailRequestDto.java
  src/main/java/hanium/where2go/domain/restaurant/dto/MenuResponseDto.java
  src/main/java/hanium/where2go/domain/restaurant/dto/RestaurantDto.java
  src/main/java/hanium/where2go/domain/restaurant/dto/RestaurantEnrollRequestDto.java
  src/main/java/hanium/where2go/domain/restaurant/dto/RestaurantEnrollResponseDto.java
  src/main/java/hanium/where2go/domain/restaurant/dto/RestaurantMenuBoardUpdateRequestDto.java
  src/main/java/hanium/where2go/domain/restaurant/dto/RestaurantMenuBoardUpdateResponseDto.java
  src/main/java/hanium/where2go/domain/restaurant/dto/RestaurantMenuDto.java
  src/main/java/hanium/where2go/domain/restaurant/dto/RestaurantMenuEnrollRequestDto.java
  src/main/java/hanium/where2go/domain/restaurant/dto/RestaurantMenuEnrollResponseDto.java
  src/main/java/hanium/where2go/domain/restaurant/dto/RestaurantMenuUpdateRequestDto.java
  src/main/java/hanium/where2go/domain/restaurant/dto/RestaurantMenuUpdateResponseDto.java
  src/main/java/hanium/where2go/domain/restaurant/dto/RestaurantUpdateRequestDto.java
  src/main/java/hanium/where2go/domain/restaurant/dto/RestaurantUpdateResponseDto.java
  src/main/java/hanium/where2go/domain/restaurant/entity/Menu.java
  src/main/java/hanium/where2go/domain/restaurant/entity/MenuBoard.java
  src/main/java/hanium/where2go/domain/restaurant/entity/Restaurant.java
  src/main/java/hanium/where2go/domain/restaurant/service/MenuService.java
  src/main/java/hanium/where2go/domain/restaurant/service/RestaurantService.java
Labels: enhancement

#67 [Fix] #65: Address 엔티티 관련 버그 수정
  src/main/java/hanium/where2go/domain/restaurant/dto/RestaurantDto.java
  src/main/java/hanium/where2go/domain/restaurant/entity/Restaurant.java
  src/main/java/hanium/where2go/domain/restaurant/service/RestaurantService.java
Labels: fix

#77 [Feature] #75 회원 탈퇴 및 비밀번호 변경
  src/main/java/hanium/where2go/domain/customer/controller/CustomerController.java
  src/main/java/hanium/where2go/domain/customer/dto/CustomerResetPasswordRequestDto.java
  src/main/java/hanium/where2go/domain/customer/service/CustomerService.java
  src/main/java/hanium/where2go/domain/user/entity/User.java
Labels: enhancement
